Support upstream (github) deployment templates

diff --git a/bin/genesis b/bin/genesis
--- a/bin/genesis
+++ b/bin/genesis
@@ -1,5 +1,5 @@
 #!/bin/bash
-VERSION=1.2.2
+VERSION=1.3.0
 
 USERNAME=$(whoami)
 CANON_REPO=https://github.com/starkandwayne/genesis
@@ -1476,6 +1476,7 @@ cmd_new_deployment() {
 	local dtype="normal"
 	local root=$(pwd)
 	local name=""
+	local template=""
 
 	while (( $# )); do
 		arg=$1 ; shift
@@ -1484,17 +1485,32 @@ cmd_new_deployment() {
 			dtype=$1
 			shift
 			;;
+		(-T|--template)
+			template=$1
+			shift
+			;;
 		(-r|--root)
 			root=$1
 			shift
 			;;
 		(*)
-			name=$arg
+			name=${arg%-deployment*}
 			shift
 			;;
 		esac
 	done
 
+	if [[ -n ${template} ]]; then
+		if [[ ${template} != ?*/?* ]]; then
+			template="starkandwayne/${template}"
+		fi
+		template="${template%%-deployment*}-deployment"
+
+		if [[ -z ${name} ]]; then
+			name=${template##*/}
+			name=${name#-deployment*}
+		fi
+	fi
 	if [[ -z ${name:-} ]]; then
 		echo >&2 "USAGE: genesis new deployment [options] name"
 		exit 1
@@ -1508,6 +1524,19 @@ cmd_new_deployment() {
 	if [[ -d "${root}/${name}-deployments" ]]; then
 		echo >&2 "Error: target directory ${root}/${name}-deployments already exists!"
 		exit 1
+	fi
+
+	if [[ -n ${template} ]]; then
+		local url=https://github.com/${template}
+		set -e
+		echo "cloning from template ${url}"
+		git clone --origin upstream ${url} ${root}/${name}-deployments
+		cd ${root}/${name}-deployments
+		git config --remove-section branch.master
+		cmd_embed >/dev/null
+		git add bin/genesis
+		git commit -m "Initial clone of templated ${name} deployment"
+		exit 0
 	fi
 
 	case ${dtype} in
@@ -1554,11 +1583,41 @@ EOF
 }
 
 cmd_new_site() {
-	local name=${1:?USAGE: genesis new site NAME}
+	local name=""
+	local template=""
+
+	while (( $# )); do
+		arg=$1 ; shift
+		case ${arg} in
+		(-T|--template)
+			template=$1
+			shift
+			;;
+		(*)
+			name=${arg}
+			;;
+		esac
+	done
+
+	if [[ -z ${name} ]]; then
+		echo >&2 "USAGE: genesis new site [options] name"
+		exit 1
+	fi
 
 	setup
 	if [[ -d "${DEPLOYMENT_ROOT}/${name}" ]]; then
 		echo "Site ${name} already exists"
+		exit 0
+	fi
+
+	if [[ -n ${template} ]]; then
+		if [[ ! -d ${DEPLOYMENT_ROOT}/.templates/${template} ]]; then
+			echo >&2 "Site template '${template}' not found..."
+			exit 2
+		fi
+
+		cp -a ${DEPLOYMENT_ROOT}/.templates/${template} ${DEPLOYMENT_ROOT}/${name}
+		create_site_readme ${name} >${DEPLOYMENT_ROOT}/${name}/README
 		exit 0
 	fi
 
