Put release notes in the right location

diff --git a/ci/scripts/release b/ci/scripts/release
--- a/ci/scripts/release
+++ b/ci/scripts/release
@@ -67,14 +67,15 @@ header "Release Notes for v${VERSION}"
 header="$(sed -i -e '1{w /dev/stdout' -e 'd}' "${RELEASE_NOTES_PATH}")"
 re="^<!--- Release Notes for v${VERSION} -- Do not move --->$"
 if [[ "$header" =~ $re ]] ; then
-  sed -i  '/^---8<--- This line and everything below will be ignored ---8<---$/,$d' "${RELEASE_NOTES_PATH}"
-  cat "${RELEASE_NOTES_PATH}"
+	sed -i '/^---8<--- This line and everything below will be ignored ---8<---$/,$d' "${RELEASE_NOTES_PATH}"
+	cat "${RELEASE_NOTES_PATH}"
+	cp "${RELEASE_NOTES_PATH}" "$RELEASE_ROOT/notes.md"
 else
-  echo "Failed to find release notes for v$VERSION in $RELEASE_NOTES_PATH.  Found this instead:"
-  echo
-  echo "$header"
-  cat "${RELEASE_NOTES_PATH}"
-  exit 1
+	echo "Failed to find release notes for v$VERSION in $RELEASE_NOTES_PATH.	Found this instead:"
+	echo
+	echo "$header"
+	cat "${RELEASE_NOTES_PATH}"
+	exit 1
 fi
 
 if [[ -z "${PRERELEASE}" && "$DEVELOP_BRANCH" != "$RELEASE_BRANCH" ]] ; then
