[ci] Move to pipes.starkandwayne.com

diff --git a/ci/scripts/shipit b/ci/scripts/shipit
--- a/ci/scripts/shipit
+++ b/ci/scripts/shipit
@@ -1,5 +1,4 @@
 #!/bin/bash
-
 #
 # ci/scripts/shipit
 #
@@ -7,35 +6,48 @@
 # and managing release notes for a software pipeline
 #
 # author:  James Hunt <james@niftylogic.com>
-# created: 2016-03-30
-
-auto_sed() {
-  file=$1
-  shift
-  cmd=$1
-  shift
-
-  if [[ "$(uname -s)" == "Darwin" ]]; then
-    sed -E -i='' -e "$cmd" ${file}
-  else
-    sed -r -i -e "$cmd" ${file}
-  fi
-}
 
 set -eu
+DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
-if [[ -z ${VERSION_FROM} ]]; then
-  echo >&2 "VERSION_FROM environment variable not set, or empty.  Did you misconfigure Concourse?"
-  exit 2
-fi
+header() {
+  echo
+  echo "###############################################"
+  echo
+  echo $*
+  echo
+}
+
+######
+######
+######
+header "Checking the Concourse Pipeline Environment"
+envok=0
+checkenv() {
+  local name=$1
+  local val=$2
+
+  if [[ -z "$val" ]]; then
+    echo >&2 "The $name variable must be set."
+    envok=1
+  fi
+}
+checkenv GIT_NAME     "${GIT_NAME:-}"
+checkenv GIT_EMAIL    "${GIT_EMAIL:-}"
+checkenv VERSION_FROM "${VERSION_FROM:-}"
 if [[ ! -f ${VERSION_FROM} ]]; then
-  echo >&2 "Version file (${VERSION_FROM}) not found.  Did you misconfigure Concourse?"
+  echo >&2 "Version file (${VERSION_FROM}) not found."
+  envok=1
   exit 2
 fi
 VERSION=$(cat ${VERSION_FROM})
 if [[ -z ${VERSION} ]]; then
-  echo >&2 "Version file (${VERSION_FROM}) was empty.  Did you misconfigure Concourse?"
-  exit 2
+  echo >&2 "Version file (${VERSION_FROM}) was empty."
+  envok=1
+fi
+if [[ $envok != 0 ]]; then
+  echo >&2 "Is your Concourse Pipeline misconfigured?"
+  exit 1
 fi
 
 if [[ ! -f ${REPO_ROOT}/ci/release_notes.md ]]; then
@@ -43,49 +55,52 @@ if [[ ! -f ${REPO_ROOT}/ci/release_notes.md ]]; then
   exit 1
 fi
 
-###############################################################
 
-ROOT=$( cd "$( dirname "${BASH_SOURCE[0]}" )/../.." && pwd )
-
-pushd $REPO_ROOT
-mkdir artifacts
-
-if [[ ! -d ${BIN_DIR} ]]; then
-	echo "${BIN_DIR} does not exist as a directory inside ${REPO_ROOT}"
-	exit 1
-fi
-
-./pack ${VERSION}
-mv genesis-${VERSION} artifacts/genesis
-artifacts/genesis -v | grep ${VERSION}
-
+######
+######
+######
+header "Compiling the release..."
+pushd ${REPO_ROOT}
+make shipit
 popd
 
+
+######
+######
+######
+header "Preparing the release assets"
 echo "v${VERSION}"                         > ${RELEASE_ROOT}/tag
 echo "${RELEASE_NAME} v${VERSION}"         > ${RELEASE_ROOT}/name
 mv ${REPO_ROOT}/ci/release_notes.md          ${RELEASE_ROOT}/notes.md
 mv ${REPO_ROOT}/artifacts                    ${RELEASE_ROOT}/artifacts
 
 cat > ${RELEASE_ROOT}/notification <<EOF
-<!here> New ${RELEASE_NAME} v${VERSION} released!
+New ${RELEASE_NAME} v${VERSION} released!
 EOF
 
 
-# GIT!
+######
+######
+######
+header "Pushing changes to git"
 if [[ -z $(git config --global user.email) ]]; then
-  git config --global user.email "ci@starkandwayne.com"
+  git config --global user.email "${GIT_EMAIL}"
 fi
 if [[ -z $(git config --global user.name) ]]; then
-  git config --global user.name "CI Bot"
+  git config --global user.name "${GIT_NAME}"
 fi
 
 (cd ${REPO_ROOT}
- git stash
  git merge --no-edit ${BRANCH}
- git stash pop
  git add -A
  git status
  git commit -m "release v${VERSION}")
 
 # so that future steps in the pipeline can push our changes
 cp -a ${REPO_ROOT} ${REPO_OUT}/git
+
+echo
+echo
+echo
+echo "SUCCESS"
+exit 0
