Update tests for deploy output changes

diff --git a/t/src/fancy/hooks/secrets b/t/src/fancy/hooks/secrets
--- a/t/src/fancy/hooks/secrets
+++ b/t/src/fancy/hooks/secrets
@@ -1,12 +1,11 @@
 #!/bin/bash
 set -eu
-exec 2>&1
 
 # for brevity's sake
 prefix=secret/$GENESIS_VAULT_PREFIX
 
 # the tests will want to know how we were called...
-safe --quiet set $prefix/args all="{$@}"
+safe --quiet set "$prefix/args" all="{$@}"
 
 # ... and what our environment was
 safe --quiet set $prefix/env \
@@ -28,22 +27,22 @@ case $GENESIS_SECRET_ACTION in
 check)
   rc=0
   if ! safe --quiet check $prefix/admin:password; then
-    echo "[admin:password] is missing"
+    echo >&2 "[admin:password] is missing"
     rc=1
   fi
   [[ $rc == 0 ]] || exit $rc
-  echo "all secrets and certs present!"
+  echo >&2 "all secrets and certs present!"
   ;;
 
 add)
   if ! safe --quiet check $prefix/admin:password; then
-    echo "[admin:password] generating new administrator password"
+    echo >&2 "[admin:password] generating new administrator password"
     safe --quiet gen $prefix/admin password
   fi
   ;;
 
 rotate)
-  echo "[admin:password] rotating administrator password"
+  echo >&2 "[admin:password] rotating administrator password"
   safe --quiet gen $prefix/admin password
   # FIXME: how are we going to do --force?
   ;;
